name: Release

on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-release:
    name: Release on github
    runs-on: ubuntu-latest
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
      changes: ${{ steps.changesets.outputs.changes }}
    steps:
      - uses: ./.github/actions/setup
        
      - name: Version and Create PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn bump
          commit: "chore(changeset): version packages"
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-release:
    name: Publish to npm
    needs: github-release
    if: needs.github-release.outputs.hasChangesets == 'true' && github.repository_owner == 'pmndrs'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
        
      - name: Publish to npm
        run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}